Algoritmo "exercicio_dois"

Var
    n1, n2: real


Inicio

    escreva("Digite o 1º número: ")
    leia(n1)
    escreva("Digite o 2º número: ")
    leia(n2)
    
    se(n1 > n2)  entao
       escreva("O maior número foi: ", n1)
         senao
            se (n2 > n1) entao
            escreva("O maior número foi: ", n2)
    senao
    escreva("Os númeos são iguais")
    
    fimse
         fimse

    
Fimalgoritmo