algoritmo "Exercicio_um"

Var
    v1: vetor [1..5] de inteiro
    v2: vetor [1..5] de inteiro
    contador : inteiro
Inicio
      para contador de 1 ate 5 faca
           escreva("Digite o ",contador,"º número : ")
           leia(v1[contador])
            v2[contador]<- v1[contador]
      fimpara
       para contador de 1 ate 5 faca
           escreval(v1[contador], v2[contador])
      fimpara
fimalgoritmo